# Generated by Django 5.0.3 on 2024-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
