# Generated by Django 5.0.3 on 2024-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saftytips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guardian_email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
